version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg15 # Use an image that includes pgvector
    container_name: devmind_postgres
    environment:
      POSTGRES_USER: devmind_user
      POSTGRES_PASSWORD: devmind_password
      POSTGRES_DB: devmind_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: devmind_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  # Optional: pgAdmin for database management (useful for debugging)
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: devmind_pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - postgres
  #   restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
